export const FETCH_PLACES = "FETCH_PLACES";
export const SELECT_PLACE = "SELECT_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";